-- MMI Minimart product catalog seed script
-- Generated from KATALOG_UTAMA_MMI.xlsx, sheet 'INVENTARIS METER'
-- Stock/inventory columns intentionally excluded.
-- Selling price = source formula: ROUNDUP((wholesale_unit*1.032483*1.07)/500,0)*500
-- See catalog_issues table for known data problems carried over from the source file.

DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    source_no INTEGER NOT NULL,
    name_latin TEXT,
    name_chinese TEXT,
    category_latin TEXT,
    category_chinese TEXT,
    size TEXT,
    unit TEXT,
    selling_price_idr INTEGER,
    image_path TEXT,
    flagged INTEGER NOT NULL DEFAULT 0,
    flag_reason TEXT
);

DROP TABLE IF EXISTS catalog_issues;
CREATE TABLE catalog_issues (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER,
    source_no INTEGER,
    sheet_row INTEGER,
    issue TEXT NOT NULL
);

INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (1, 1, 'Vsoy', 'åå³è±å¥¶', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '200ml', 'btl / ç¶', 8500, 'images/001.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (2, 2, 'Bear Brand Steril', 'çæ æ¶æ¯çå¥¶', 'Susu', NULL, '189ml', 'kaleng', 11500, 'images/002.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (3, 3, 'Collagena', 'è¶åèç½ç­èå¥¶', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '189ml', 'kaleng / ç½', 14500, 'images/003.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (4, 4, 'Tujuh Kurma', 'æ¤°æ£ç­èå¥¶', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '189ml', 'btl / ç¶', 10000, NULL, 1, 'No product photo embedded in source.');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (5, 5, 'Ultra UHT', 'çå¥¶', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '250ml', 'btl / ç¶', 8000, 'images/005.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (6, 6, 'Greenfields UHT', 'å¨è çå¥¶', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '250ml', 'btl / ç¶', 7500, 'images/006.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (7, 7, 'Cimory', 'é¥®ç¨é¸å¥¶', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '240ml', 'btl / ç¶', 10000, 'images/007.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (8, 8, NULL, 'ç¾ç¦å·§ååéº¦è½é¥®æ', 'Susu', 'çå¥¶ä¸ä¹³å¶å', '220ml', 'btl / ç¶', 9500, 'images/008.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (9, 9, 'Mizone coco boost', 'ç­æ¸è¿å¨é¥®æ', 'Minuman', 'é¥®æ', '500ml', 'btl / ç¶', 5000, 'images/009.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (10, 10, 'Sari Kacang Hijau', 'ç»¿è±é¥®æ', 'Minuman', 'é¥®æ', '150ml', 'btl / ç¶', 3500, 'images/010.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (11, 11, 'Buavita', 'ææ±', 'Minuman', 'é¥®æ', '245ml', 'btl / ç¶', 6500, 'images/011.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (12, 12, 'Tebs', 'ç¢³é¸é¥®æ', 'Minuman', 'é¥®æ', '500ml', 'btl / ç¶', 7500, NULL, 1, 'No product photo embedded in source.');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (13, 13, NULL, 'çç«çä»èé¥®æ', 'Minuman', 'é¥®æ', '310ml', 'kaleng / ç½', 6000, 'images/013.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (14, 14, 'Cap Badak', 'æ¸åé¥®æ', 'Minuman', 'é¥®æ', '500ml', 'btl / ç¶', 9000, 'images/014.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (15, 15, 'You C 1000 C1000', 'ä¼ ç»´çç´ é¥®å', 'Minuman', NULL, '140ml', 'btl', 7000, 'images/015.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (16, 16, 'Floridina', 'æ©å³ææ±é¥®æ', 'Minuman', 'é¥®æ', '350ml', 'btl / ç¶', 5500, 'images/016.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (17, 17, 'ICHITAN Brown Sugar', 'è¶ç· é»ç³å³é¥®æ', 'Minuman', NULL, '300ml', 'btl', 8000, 'images/017.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (18, 18, 'NU Milk Tea NU', 'å¥¶è¶', 'Minuman', NULL, '330ml', 'btl', 8000, 'images/018.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (19, 19, 'Coca Cola', 'å¯å£å¯ä¹', 'Minuman', 'é¥®æ', '390ml', 'btl / ç¶', 5500, 'images/019.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (20, 20, 'Yakult Light', 'å»ä¹å¤ä½ç³', 'Minuman', NULL, '5x65ml', 'btl', 16500, 'images/020.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (21, 21, 'Adem Sari Sparkling', 'é¿å¾·å§è¨éæ¸é·æ°æ³¡é¥®', 'Minuman', NULL, '320ml', 'kaleng', 9000, 'images/021.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (22, 22, 'Le Minerale 5000', 'ç¿æ³æ°´ æ¯«å', 'Air Mineral', 'ç¿æ³æ°´', '5000ml', 'btl / ç¶', 17000, 'images/022.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (23, 23, 'Le Minerale 1500', 'ç¿æ³æ°´ æ¯«å', 'Air Mineral', 'ç¿æ³æ°´', '1500ml', 'btl / ç¶', 5500, 'images/023.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (24, 24, 'Ovaltine 3in1', 'é¿åç° ä¸åä¸', 'Coklat Bubuk', NULL, '18Ã33gr', 'pcs', 71000, 'images/024.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (25, 25, 'Indocafe', 'ä¸åä¸å³æº¶åå¡', 'Kopi & Teh', 'åå¡ä¸è¶', '10x20gr', 'pcs / ä»¶', 18000, 'images/025.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (26, 26, 'Luwak', 'ä½ç³ç½åå¡', 'Kopi & Teh', 'åå¡ä¸è¶', '10x20gr', 'pcs / ä»¶', 10000, 'images/026.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (27, 27, 'Good Day', 'å³æº¶åå¡', 'Kopi & Teh', 'åå¡ä¸è¶', '10x22gr', 'pcs / ä»¶', 22000, 'images/027.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (28, 28, 'Max Tea', 'æè¶', 'Kopi & Teh', 'åå¡ä¸è¶', '5x25gr', 'pcs / ä»¶', 14000, 'images/028.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (29, 29, 'Indomie', 'æ¹ä¾¿é¢', 'Mie & Pasta', 'é¢æ¡ä¸æé¢', '80gr', 'pcs / ä»¶', 3500, 'images/029.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (30, 30, 'Pop Mie', 'æ¯é¢', 'Mie & Pasta', 'é¢æ¡ä¸æé¢', '77gr', 'pcs / ä»¶', 6000, 'images/030.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (31, 31, NULL, 'ä¸å»è¾£é¸¡çé¢', 'Mie & Pasta', 'é¢æ¡ä¸æé¢', '140gr', 'pcs / ä»¶', 18000, 'images/031.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (32, 32, NULL, 'åå¿è¾æé¢', 'Mie & Pasta', 'é¢æ¡ä¸æé¢', '120gr', 'pcs / ä»¶', 15000, 'images/032.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (33, 33, NULL, 'æ¡æ ¼å³é£çéº¦ï¼çº¢è²åè£ï¼', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '1,2 Kg', 'pcs / ä»¶', 60000, 'images/033.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (34, 34, 'Fitbar', 'å·§ååè°·ç©æ£', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '20gr', 'pcs / ä»¶', 5000, 'images/034.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (35, 35, 'Beng Beng Maxx', 'å·§ååå¨å', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '32gr', 'pcs / ä»¶', 5000, 'images/035.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (36, 36, 'SilverQueen', 'å·§åå', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '52gr', 'pcs / ä»¶', 17500, 'images/036.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (37, 37, 'Mayasi', 'çè±ç', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '65gr', 'pcs / ä»¶', 10500, 'images/037.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (38, 38, 'Dua Kelinci', 'è±ç', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '370gr', 'pcs / ä»¶', 31500, 'images/038.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (39, 39, 'Garuda', 'è±ç', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '350gr', 'pcs / ä»¶', 39000, 'images/039.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (40, 40, 'Chitato', 'è¯ç', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '14gr', 'pcs / ä»¶', 3000, 'images/040.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (41, 41, 'Qtela', 'èç', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '60gr', 'pcs / ä»¶', 6500, 'images/041.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (42, 42, 'Rebo', 'èµè±ç±½', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '140gr', 'pcs / ä»¶', 12000, 'images/042.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (43, 43, 'Roma', 'å¨éº¦é¥¼å¹²', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '149gr', 'pcs / ä»¶', 8500, 'images/043.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (44, 44, 'Regal', 'çä¸½é¥¼å¹²', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '120gr', 'pcs / ä»¶', 14500, 'images/044.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (45, 45, 'Ritz', 'èå£«é¥¼å¹²', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '91gr', 'pcs / ä»¶', 8500, 'images/045.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (46, 46, 'Good Time', 'æ²å¥é¥¼å¹²', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '72gr', 'pcs / ä»¶', 9000, 'images/046.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (47, 47, 'Nabati', 'å¨åé¥¼å¹²', 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '75gr', 'pcs / ä»¶', 5500, 'images/047.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (48, 48, 'Kopiko', 'åå¡ç³', 'Permen', 'ç³æ', '105g', 'pcs / ä»¶', 9000, 'images/048.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (49, 49, 'Kopiko', 'åå¡ç³', 'Permen', 'ç³æ', '165g', 'pcs / ä»¶', 10500, 'images/049.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (50, 50, 'Lifebuoy', 'å«å®æ²æµ´é²', 'Sabun Mandi', 'æ²æµ´æ¸æ´', '100ml', 'btl / ç¶', 18000, 'images/050.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (51, 51, NULL, 'ç¢§ææ²æµ´é²', 'Sabun Mandi', 'æ²æµ´æ¸æ´', '400ml', 'pcs / ä»¶', 24500, 'images/051.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (52, 52, NULL, 'åå£«é¦ç', 'Sabun Mandi', 'æ²æµ´æ¸æ´', '70gr', 'pcs / ä»¶', 5000, 'images/052.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (53, 53, NULL, 'æµ·é£ä¸æ´åæ°´', 'Perawatan Rambut', 'å¤´åæ¤ç', '160ml/145', 'btl / ç¶', 25500, 'images/053.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (54, 54, 'Pepsodent', 'çè', 'Perawatan Mulut', 'å£èæ¤ç', '120gr', 'pcs / ä»¶', 10000, 'images/054.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (55, 55, 'Pepsodent 1', 'çå·ï¼ æ¯ï¼', 'Perawatan Mulut', 'å£èæ¤ç', '1pcs', 'pcs / ä»¶', 3500, 'images/055.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (56, 56, NULL, 'å¦®ç»´éæ´é¢ä¹³', 'Perawatan Kulit', 'ç®è¤æ¤ç', '100ml', 'pcs / ä»¶', 1500, 'images/056.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (57, 57, NULL, 'ç¢§æç·å£«æ´é¢ä¹³', 'Perawatan Kulit', 'ç®è¤æ¤ç', '100gr', 'pcs / ä»¶', 33500, 'images/057.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (58, 58, 'Rinso', 'æ´è¡£ç²', 'Detergen', 'æ´æ¶¤å', '770gr', 'pcs / ä»¶', 19500, 'images/058.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (59, 59, 'Rinso', 'æ´è¡£æ¶²', 'Detergen', 'æ´æ¶¤å', '510gr', 'pcs / ä»¶', 10500, 'images/059.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (60, 60, 'HIT', 'æè«å·é¾', 'Insektisida', 'æè«/é©±è«ç¨å', '400ml', 'btl / ç¶', 35000, NULL, 1, 'No product photo embedded in source.');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (61, 61, 'Soffell', 'é©±èå', 'Insektisida', 'æè«/é©±è«ç¨å', '60gr', 'pcs / ä»¶', 11500, 'images/061.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (62, 62, 'Paseo Smart', 'é¢å·¾çº¸', 'Tisu', 'çº¸å·¾', '540ply', 'pcs / ä»¶', 12500, 'images/062.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (63, 63, 'Mitu Pink', 'æ¹¿å·¾', 'Tisu Basah', 'æ¹¿å·¾', '10s', 'pcs / ä»¶', 4500, 'images/063.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (64, 64, 'Larisst', 'æ«å¸', 'Peralatan Bersih', 'æ¸æ´å·¥å·', '-', 'pcs / ä»¶', 45000, 'images/064.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (65, 65, 'Bagus', 'æè«ç²ç¬', 'Peralatan Lain', 'å¶ä»å®¶å±ç¨å', '1', 'pcs / ä»¶', 10000, 'images/065.jpeg', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (66, 66, 'Mustika Ratu', 'æ©æ¦æ²¹', 'Herbal', 'èæ¬ä¿å¥', '175ml', 'btl / ç¶', 45500, 'images/066.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (67, 67, 'Luwak Tokopedia WORCAS', 'ç½è£åå¡ï¼ å®æ¹åºæå®ï¼', 'Kopi & Teh', 'åå¡ä¸è¶', '100gr', 'kaleng / ç½', 354000, 'images/067.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (68, 68, 'Fjbottle', NULL, 'Lain-Lain', 'å¶ä»', '2 Liter', 'btl / ç¶', 298500, 'images/068.jpeg', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (69, 69, 'Tanpa merk', NULL, 'Lain-Lain', 'å¶ä»', '3,8 Liter', 'btl / ç¶', 309500, 'images/069.jpeg', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (70, 70, 'Siok', NULL, 'Snack & Biskuit', 'é¶é£ä¸é¥¼å¹²', '500gr', 'pcs / ä»¶', 177000, 'images/070.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (71, 71, 'ChaCha Hot & Spicy Squid Konjac', 'æ°æ°é­èç½ è¾£å³', 'Snack & Biskuit', NULL, '18gr', 'pcs / ä»¶', NULL, 'images/071.png', 1, 'Invalid price value in source cell: ''w'' (not a number).');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (72, 72, 'ChaCha Mala Squid Konjac', 'æ°æ°é­èç½ éº»è¾£', 'Snack & Biskuit', NULL, '18gr', 'pcs / ä»¶', 2000, 'images/072.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (73, 73, 'ChaCha Spicy Sour Squid Konjac', 'æ°æ°é­èç½ é¸è¾£å³', 'Snack & Biskuit', NULL, '18gr', 'pcs / ä»¶', 2000, 'images/073.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (74, 73, 'Golden Mill Shredded Crab Stick Hot & Spicy', 'éç£¨åææè¹æ³ é¦è¾£å³', 'Snack & Biskuit', NULL, '14gr', 'pcs / ä»¶', 5500, 'images/074.jpeg', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (75, 73, 'Golden Mill Shredded Crab Stick Original 14gr', 'éç£¨åææè¹æ³ åå³', 'Snack & Biskuit', NULL, '14gr', 'pcs / ä»¶', 5500, 'images/075.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (76, 74, 'Golden Mill Fish Tofu Seafood Flavour', 'éç£¨åé±¼è±è æµ·é²å³', 'Snack & Biskuit', NULL, '20gr', 'pcs / ä»¶', 5500, 'images/076.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (77, 75, 'Golden Mill Fish Tofu Hot & Spicy', 'éç£¨åé±¼è±è é¦è¾£å³', 'Snack & Biskuit', NULL, '20gr', 'pcs / ä»¶', 5500, 'images/077.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (78, 76, 'Golden Mill Fish Tofu Mala', 'éç£¨åé±¼è±è éº»è¾£å³', 'Snack & Biskuit', NULL, '20gr', 'pcs / ä»¶', 5500, 'images/078.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (79, 77, 'Bean Tendon Hot & Spicy Flavor', 'éç£¨åå å¿è±ç­ é¦è¾£å³', 'Snack & Biskuit', NULL, '110gr', 'pcs / ä»¶', 15500, 'images/079.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (80, 78, 'Roasted Tofu Hot & Spicy Flavor', 'å²ä»åè±å¹² é¦è¾£å³', 'Snack & Biskuit', NULL, '20gr', 'pcs / ä»¶', 5500, 'images/080.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (81, 79, 'Anchovy Snack Spicy Flavor', 'å²ä»æ·±æµ·å°é±¼ é¦è¾£å³', 'Snack & Biskuit', NULL, '20gr', 'pcs / ä»¶', 5500, 'images/081.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (82, 80, 'Kangshifu Braised Beef Flavor', 'åº·å¸åçº¢ç§çèé¢', 'Snack & Biskuit', NULL, '104gr', 'pcs / ä»¶', 15000, 'images/082.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (83, 81, 'Kangshifu Pickled Vegetables Beef Flavor Noodle', 'åº·å¸åèåé¸èçèé¢', 'Snack & Biskuit', NULL, '117gr', 'pcs / ä»¶', 15000, 'images/083.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (84, 82, 'Kangshifu Mushroom Chicken Flavor Noodle', 'åº·å¸å é¦èçé¸¡é¢', 'Snack & Biskuit', NULL, '110gr', 'pcs / ä»¶', 15000, 'images/084.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (85, 83, 'Kangshifu Lemon Iced Tea', 'åº·å¸åå°çº¢è¶', 'Minuman', NULL, '500ml', 'pcs / ä»¶', 15000, 'images/085.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (86, 84, 'Kangshifu Honey Jasmine Green Tea', 'åº·å¸åèèèèç»¿è¶', 'Minuman', NULL, '500ml', 'pcs / ä»¶', 15000, 'images/086.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (87, 85, 'Kangshifu Snow Pear with Rock Sugar', 'åº·å¸åå°ç³éªæ¢¨', 'Minuman', NULL, '500ml', 'pcs / ä»¶', 15000, 'images/087.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (88, 86, 'Kangshifu Sour Plum Juice', 'åº·å¸åé¸æ¢æ±¤', 'Minuman', NULL, '500ml', 'pcs / ä»¶', 15000, 'images/088.png', 0, NULL);
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (89, 87, 'Wujiang Preserved Mustard', 'ä¹æ±æ¦¨è', 'Snack & Biskuit', NULL, '60gr', 'pcs / ä»¶', NULL, 'images/089.jpeg', 1, 'No selling price set yet in source (formula evaluates blank).');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (90, 88, 'Wangzhihe Fermented Bean Curd', 'çè´åä¸­åèå­å·å¤§åèä¹³', 'Mie & Pasta', NULL, '340gr', 'pcs / ä»¶', NULL, 'images/090.jpeg', 1, 'No selling price set yet in source (formula evaluates blank).');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (91, 89, 'Yongchao Fragrant Diced Bamboo Shoots', 'æ°¸è¶é£é¦ç¬ä¸', 'Mie & Pasta', NULL, '400gr', 'pcs / ä»¶', NULL, 'images/091.jpeg', 1, 'No selling price set yet in source (formula evaluates blank).');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (92, 89, 'Yongchao Fragrant Diced Bamboo Shoots', 'æ°¸è¶é£é¦ç¬ä¸', 'Mie & Pasta', NULL, '400gr', 'pcs / ä»¶', NULL, 'images/092.jpeg', 1, 'No selling price set yet in source (formula evaluates blank).');
INSERT INTO products (id, source_no, name_latin, name_chinese, category_latin, category_chinese, size, unit, selling_price_idr, image_path, flagged, flag_reason) VALUES (93, 90, 'Yongchao Spicy Preserved Dried Radish', 'æ°¸è¶èåå¹² é¦è¾£', 'Mie & Pasta', NULL, '400gr', 'pcs / ä»¶', NULL, 'images/093.jpeg', 1, 'No selling price set yet in source (formula evaluates blank).');

INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (3, 3, 5, '2 images anchored to this row â only the first was used.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (11, 11, 13, '2 images anchored to this row â only the first was used.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (48, 48, 50, '2 images anchored to this row â only the first was used.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (59, 59, 61, '2 images anchored to this row â only the first was used.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (65, 65, 68, '5 images anchored to this row â only the first was used.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (NULL, 91, 99, 'Row numbered but has no product name at all â excluded as not a real product entry.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (NULL, 73, NULL, 'source NO 73 used for 3 different rows in the original sheet (ids [73, 74, 75]) â not a duplicate product, just reused numbering. Each kept as its own row.');
INSERT INTO catalog_issues (product_id, source_no, sheet_row, issue) VALUES (NULL, 89, NULL, 'source NO 89 used for 2 different rows in the original sheet (ids [91, 92]) â not a duplicate product, just reused numbering. Each kept as its own row.');
