// Ported from android/app/src/main/java/com/minimart/field/ui/cashier/Strings.kt
// so the desktop till reads identically to the tablet, plus a few new
// strings for the manual sync button (desktop-only feature).
export const LANGS = ['EN', 'ZH', 'ID']

export function nextLang(lang) {
  return LANGS[(LANGS.indexOf(lang) + 1) % LANGS.length]
}

const STRINGS = {
  EN: {
    title: 'Cashier — New Sale',
    enterWorkerId: 'Enter worker ID',
    employeeId: 'Employee ID',
    lookUpWorker: 'Look Up Worker',
    change: 'Change',
    noProductsCached: 'No products cached yet. Connect to the internet once to download the catalog.',
    add: 'Add',
    total: 'Total',
    confirmSale: 'Confirm Sale',
    saleComplete: 'Sale complete',
    saleFailed: 'Sale failed',
    ok: 'OK',
    chargeTitle: 'Charge Sale To Worker',
    cancel: 'Cancel',
    workerNotFound: 'Worker not found in cached directory.',
    insufficientBalance: 'Insufficient balance for this worker.',
    staleBanner: '⚠ Using built-in starter data — this till has never synced with the server. Balances shown may be out of date. Connect to the internet to get live data.',
    outOfStock: 'Out of stock',
    left: 'left',
    idLabel: 'ID',
    sync: 'Sync',
    syncing: 'Syncing…',
    pendingSales: 'pending',
    syncSuccess: 'Synced',
    syncFailure: 'Sync failed',
    lastSynced: 'Last synced',
    never: 'never',
    topUp: 'Top Up',
    topUpTitle: 'Top Up Worker Balance',
    cashReceived: 'Cash received',
    noteOptional: 'Note (optional)',
    currentBalance: 'Current balance',
    topUpComplete: 'Top-up complete',
    topUpFailed: 'Top-up failed',
    newBalance: 'New balance',
    invalidAmount: 'Enter an amount greater than 0.',
    tabShop: 'Shop',
    tabTransactions: 'Transactions',
    noTransactions: 'No transactions yet.',
    colType: 'Type',
    colWorker: 'Worker',
    colAmount: 'Amount',
    colStatus: 'Status',
    colDetail: 'Detail',
    colCreated: 'Created',
    saleLabel: 'Sale',
    topUpLabel: 'Top-up',
    statusPending: 'pending',
    statusSynced: 'synced',
    statusFailed: 'failed',
    searchWorkerPlaceholder: 'Search by name or ID',
    noMatches: 'No matching workers',
    confirmCharge: 'Confirm Charge',
    balanceAfter: 'Balance after',
  },
  ZH: {
    title: '收银 — 新订单',
    enterWorkerId: '输入员工编号',
    employeeId: '员工编号',
    lookUpWorker: '查找员工',
    change: '更换',
    noProductsCached: '尚未缓存商品，请连接网络下载商品目录。',
    add: '添加',
    total: '总计',
    confirmSale: '确认销售',
    saleComplete: '销售完成',
    saleFailed: '销售失败',
    ok: '确定',
    chargeTitle: '选择付款员工',
    cancel: '取消',
    workerNotFound: '未在缓存目录中找到该员工。',
    insufficientBalance: '该员工余额不足。',
    staleBanner: '⚠ 正在使用内置初始数据 — 此收银机尚未与服务器同步，显示的余额可能不是最新的。请连接网络获取实时数据。',
    outOfStock: '缺货',
    left: '剩余',
    idLabel: '编号',
    sync: '同步',
    syncing: '同步中…',
    pendingSales: '待同步',
    syncSuccess: '已同步',
    syncFailure: '同步失败',
    lastSynced: '上次同步',
    never: '从未',
    topUp: '充值',
    topUpTitle: '为员工余额充值',
    cashReceived: '收到现金',
    noteOptional: '备注（可选）',
    currentBalance: '当前余额',
    topUpComplete: '充值完成',
    topUpFailed: '充值失败',
    newBalance: '新余额',
    invalidAmount: '请输入大于 0 的金额。',
    tabShop: '商店',
    tabTransactions: '交易记录',
    noTransactions: '暂无交易记录。',
    colType: '类型',
    colWorker: '员工',
    colAmount: '金额',
    colStatus: '状态',
    colDetail: '详情',
    colCreated: '创建时间',
    saleLabel: '销售',
    topUpLabel: '充值',
    statusPending: '待处理',
    statusSynced: '已同步',
    statusFailed: '失败',
    searchWorkerPlaceholder: '按姓名或编号搜索',
    noMatches: '未找到匹配员工',
    confirmCharge: '确认扣款',
    balanceAfter: '扣款后余额',
  },
  ID: {
    title: 'Kasir — Penjualan Baru',
    enterWorkerId: 'Masukkan ID pekerja',
    employeeId: 'ID Karyawan',
    lookUpWorker: 'Cari Pekerja',
    change: 'Ganti',
    noProductsCached: 'Belum ada produk tersimpan. Sambungkan ke internet untuk mengunduh katalog.',
    add: 'Tambah',
    total: 'Total',
    confirmSale: 'Konfirmasi Penjualan',
    saleComplete: 'Penjualan berhasil',
    saleFailed: 'Penjualan gagal',
    ok: 'OK',
    chargeTitle: 'Bebankan Penjualan Ke Pekerja',
    cancel: 'Batal',
    workerNotFound: 'Pekerja tidak ditemukan di direktori tersimpan.',
    insufficientBalance: 'Saldo pekerja ini tidak mencukupi.',
    staleBanner: '⚠ Menggunakan data awal bawaan — kasir ini belum pernah tersinkron dengan server. Saldo yang ditampilkan mungkin tidak terbaru. Sambungkan ke internet untuk data langsung.',
    outOfStock: 'Stok habis',
    left: 'tersisa',
    idLabel: 'ID',
    sync: 'Sinkronkan',
    syncing: 'Menyinkronkan…',
    pendingSales: 'tertunda',
    syncSuccess: 'Berhasil disinkronkan',
    syncFailure: 'Sinkronisasi gagal',
    lastSynced: 'Terakhir disinkronkan',
    never: 'belum pernah',
    topUp: 'Top Up',
    topUpTitle: 'Top Up Saldo Pekerja',
    cashReceived: 'Uang tunai diterima',
    noteOptional: 'Catatan (opsional)',
    currentBalance: 'Saldo saat ini',
    topUpComplete: 'Top up berhasil',
    topUpFailed: 'Top up gagal',
    newBalance: 'Saldo baru',
    invalidAmount: 'Masukkan jumlah lebih besar dari 0.',
    tabShop: 'Toko',
    tabTransactions: 'Transaksi',
    noTransactions: 'Belum ada transaksi.',
    colType: 'Jenis',
    colWorker: 'Pekerja',
    colAmount: 'Jumlah',
    colStatus: 'Status',
    colDetail: 'Detail',
    colCreated: 'Dibuat',
    saleLabel: 'Penjualan',
    topUpLabel: 'Top up',
    statusPending: 'tertunda',
    statusSynced: 'tersinkron',
    statusFailed: 'gagal',
    searchWorkerPlaceholder: 'Cari berdasarkan nama atau ID',
    noMatches: 'Tidak ada pekerja yang cocok',
    confirmCharge: 'Konfirmasi Pembayaran',
    balanceAfter: 'Saldo setelah',
  },
}

export function strings(lang) {
  return STRINGS[lang] || STRINGS.EN
}
