// Ported from android/app/src/main/java/com/minimart/field/ui/cashier/Strings.kt
// so the desktop till reads identically to the tablet, plus a few new
// strings for the manual sync button (desktop-only feature).
export const LANGS = ['EN', 'ZH', 'ID']

export function nextLang(lang) {
  return LANGS[(LANGS.indexOf(lang) + 1) % LANGS.length]
}

const STRINGS = {
  EN: {
    title: 'Cashier — New Sale',
    enterWorkerId: 'Enter worker ID',
    employeeId: 'Employee ID',
    lookUpWorker: 'Look Up Worker',
    change: 'Change',
    noProductsCached: 'No products cached yet. Connect to the internet once to download the catalog.',
    add: 'Add',
    total: 'Total',
    confirmSale: 'Confirm Sale',
    saleComplete: 'Sale complete',
    saleFailed: 'Sale failed',
    ok: 'OK',
    chargeTitle: 'Charge Sale To Worker',
    cancel: 'Cancel',
    workerNotFound: 'Worker not found in cached directory.',
    insufficientBalance: 'Insufficient balance for this worker.',
    staleBanner: '⚠ Using built-in starter data — this till has never synced with the server. Balances shown may be out of date. Connect to the internet to get live data.',
    outOfStock: 'Out of stock',
    left: 'left',
    idLabel: 'ID',
    sync: 'Sync',
    syncing: 'Syncing…',
    pendingSales: 'pending',
    syncSuccess: 'Synced',
    syncFailure: 'Sync failed',
    lastSynced: 'Last synced',
    never: 'never',
    topUp: 'Top Up',
    topUpTitle: 'Top Up Worker Balance',
    cashReceived: 'Cash received',
    noteOptional: 'Note (optional)',
    currentBalance: 'Current balance',
    topUpComplete: 'Top-up complete',
    topUpFailed: 'Top-up failed',
    newBalance: 'New balance',
    invalidAmount: 'Enter an amount greater than 0.',
    tabShop: 'Shop',
    tabTransactions: 'Transactions',
    noTransactions: 'No transactions yet.',
    colType: 'Type',
    colWorker: 'Worker',
    colAmount: 'Amount',
    colStatus: 'Status',
    colDetail: 'Detail',
    colCreated: 'Created',
    saleLabel: 'Sale',
    topUpLabel: 'Top-up',
    statusPending: 'pending',
    statusSynced: 'synced',
    statusFailed: 'failed',
    searchWorkerPlaceholder: 'Search by name or ID',
    noMatches: 'No matching workers',
    confirmCharge: 'Confirm Charge',
    balanceAfter: 'Balance after',
    tabInventory: 'Inventory',
    colAction: 'Action',
    undo: 'Undo',
    edit: 'Edit',
    confirmUndo: 'Confirm Undo',
    undoConfirmTitle: 'Undo this transaction?',
    undoSaleSyncedMsg: "This will restore stock and refund {amount} to {worker}'s balance.",
    undoSaleLocalMsg: 'This sale has not synced yet. Undoing will remove it from the queue and restore stock and balance locally.',
    undoTopUpMsg: "This will reverse the top-up and debit {amount} from {worker}'s balance.",
    undoIrreversible: 'This cannot be undone.',
    undoDone: 'Undo complete',
    undoDoneBody: 'The transaction has been undone.',
    undoFailed: 'Undo failed',
    statusRefunded: 'refunded',
    statusReversed: 'reversed',
    addItem: 'Add Item',
    itemName: 'Item Name',
    itemNameZh: 'Chinese Name',
    uom: 'UOM',
    sellingPrice: 'Selling Price',
    category: 'Category',
    subCategory: 'Sub Category',
    save: 'Save',
    stock: 'Stock',
    adjust: 'Adjust',
    productCreated: 'Product added',
    productCreateFailed: 'Failed to add product',
    retryLoad: 'Retry',
    loadingProducts: 'Loading products…',
    noProductsYet: 'No products yet.',
    nameRequired: 'Enter an item name.',
    priceRequired: 'Enter a selling price greater than 0.',
    stockUpdateFailed: 'Failed to update stock',
    colName: 'Name',
    colCategory: 'Category',
    colUom: 'UOM',
    colPrice: 'Price',
    colStock: 'Stock',
  },
  ZH: {
    title: '收银 — 新订单',
    enterWorkerId: '输入员工编号',
    employeeId: '员工编号',
    lookUpWorker: '查找员工',
    change: '更换',
    noProductsCached: '尚未缓存商品，请连接网络下载商品目录。',
    add: '添加',
    total: '总计',
    confirmSale: '确认销售',
    saleComplete: '销售完成',
    saleFailed: '销售失败',
    ok: '确定',
    chargeTitle: '选择付款员工',
    cancel: '取消',
    workerNotFound: '未在缓存目录中找到该员工。',
    insufficientBalance: '该员工余额不足。',
    staleBanner: '⚠ 正在使用内置初始数据 — 此收银机尚未与服务器同步，显示的余额可能不是最新的。请连接网络获取实时数据。',
    outOfStock: '缺货',
    left: '剩余',
    idLabel: '编号',
    sync: '同步',
    syncing: '同步中…',
    pendingSales: '待同步',
    syncSuccess: '已同步',
    syncFailure: '同步失败',
    lastSynced: '上次同步',
    never: '从未',
    topUp: '充值',
    topUpTitle: '为员工余额充值',
    cashReceived: '收到现金',
    noteOptional: '备注（可选）',
    currentBalance: '当前余额',
    topUpComplete: '充值完成',
    topUpFailed: '充值失败',
    newBalance: '新余额',
    invalidAmount: '请输入大于 0 的金额。',
    tabShop: '商店',
    tabTransactions: '交易记录',
    noTransactions: '暂无交易记录。',
    colType: '类型',
    colWorker: '员工',
    colAmount: '金额',
    colStatus: '状态',
    colDetail: '详情',
    colCreated: '创建时间',
    saleLabel: '销售',
    topUpLabel: '充值',
    statusPending: '待处理',
    statusSynced: '已同步',
    statusFailed: '失败',
    searchWorkerPlaceholder: '按姓名或编号搜索',
    noMatches: '未找到匹配员工',
    confirmCharge: '确认扣款',
    balanceAfter: '扣款后余额',
    tabInventory: '库存',
    colAction: '操作',
    undo: '撤销',
    edit: '编辑',
    confirmUndo: '确认撤销',
    undoConfirmTitle: '要撤销此交易吗？',
    undoSaleSyncedMsg: '此操作将恢复库存，并退款 {amount} 到 {worker} 的余额。',
    undoSaleLocalMsg: '此销售尚未同步。撤销将从队列中移除该记录，并在本地恢复库存和余额。',
    undoTopUpMsg: '此操作将撤销该笔充值，并从 {worker} 的余额中扣除 {amount}。',
    undoIrreversible: '此操作无法撤销。',
    undoDone: '撤销完成',
    undoDoneBody: '该交易已被撤销。',
    undoFailed: '撤销失败',
    statusRefunded: '已退款',
    statusReversed: '已撤销',
    addItem: '添加商品',
    itemName: '商品名称',
    itemNameZh: '中文名称',
    uom: '计量单位',
    sellingPrice: '销售价格',
    category: '类别',
    subCategory: '子类别',
    save: '保存',
    stock: '库存',
    adjust: '调整',
    productCreated: '商品已添加',
    productCreateFailed: '添加商品失败',
    retryLoad: '重试',
    loadingProducts: '正在加载商品…',
    noProductsYet: '暂无商品。',
    nameRequired: '请输入商品名称。',
    priceRequired: '请输入大于 0 的销售价格。',
    stockUpdateFailed: '更新库存失败',
    colName: '名称',
    colCategory: '类别',
    colUom: '单位',
    colPrice: '价格',
    colStock: '库存',
  },
  ID: {
    title: 'Kasir — Penjualan Baru',
    enterWorkerId: 'Masukkan ID pekerja',
    employeeId: 'ID Karyawan',
    lookUpWorker: 'Cari Pekerja',
    change: 'Ganti',
    noProductsCached: 'Belum ada produk tersimpan. Sambungkan ke internet untuk mengunduh katalog.',
    add: 'Tambah',
    total: 'Total',
    confirmSale: 'Konfirmasi Penjualan',
    saleComplete: 'Penjualan berhasil',
    saleFailed: 'Penjualan gagal',
    ok: 'OK',
    chargeTitle: 'Bebankan Penjualan Ke Pekerja',
    cancel: 'Batal',
    workerNotFound: 'Pekerja tidak ditemukan di direktori tersimpan.',
    insufficientBalance: 'Saldo pekerja ini tidak mencukupi.',
    staleBanner: '⚠ Menggunakan data awal bawaan — kasir ini belum pernah tersinkron dengan server. Saldo yang ditampilkan mungkin tidak terbaru. Sambungkan ke internet untuk data langsung.',
    outOfStock: 'Stok habis',
    left: 'tersisa',
    idLabel: 'ID',
    sync: 'Sinkronkan',
    syncing: 'Menyinkronkan…',
    pendingSales: 'tertunda',
    syncSuccess: 'Berhasil disinkronkan',
    syncFailure: 'Sinkronisasi gagal',
    lastSynced: 'Terakhir disinkronkan',
    never: 'belum pernah',
    topUp: 'Top Up',
    topUpTitle: 'Top Up Saldo Pekerja',
    cashReceived: 'Uang tunai diterima',
    noteOptional: 'Catatan (opsional)',
    currentBalance: 'Saldo saat ini',
    topUpComplete: 'Top up berhasil',
    topUpFailed: 'Top up gagal',
    newBalance: 'Saldo baru',
    invalidAmount: 'Masukkan jumlah lebih besar dari 0.',
    tabShop: 'Toko',
    tabTransactions: 'Transaksi',
    noTransactions: 'Belum ada transaksi.',
    colType: 'Jenis',
    colWorker: 'Pekerja',
    colAmount: 'Jumlah',
    colStatus: 'Status',
    colDetail: 'Detail',
    colCreated: 'Dibuat',
    saleLabel: 'Penjualan',
    topUpLabel: 'Top up',
    statusPending: 'tertunda',
    statusSynced: 'tersinkron',
    statusFailed: 'gagal',
    searchWorkerPlaceholder: 'Cari berdasarkan nama atau ID',
    noMatches: 'Tidak ada pekerja yang cocok',
    confirmCharge: 'Konfirmasi Pembayaran',
    balanceAfter: 'Saldo setelah',
    tabInventory: 'Inventaris',
    colAction: 'Aksi',
    undo: 'Batalkan',
    edit: 'Ubah',
    confirmUndo: 'Konfirmasi Pembatalan',
    undoConfirmTitle: 'Batalkan transaksi ini?',
    undoSaleSyncedMsg: 'Ini akan mengembalikan stok dan mengembalikan dana {amount} ke saldo {worker}.',
    undoSaleLocalMsg: 'Penjualan ini belum tersinkron. Membatalkan akan menghapusnya dari antrean dan mengembalikan stok serta saldo secara lokal.',
    undoTopUpMsg: 'Ini akan membatalkan top up dan mendebit {amount} dari saldo {worker}.',
    undoIrreversible: 'Tindakan ini tidak dapat dibatalkan.',
    undoDone: 'Pembatalan selesai',
    undoDoneBody: 'Transaksi telah dibatalkan.',
    undoFailed: 'Pembatalan gagal',
    statusRefunded: 'dikembalikan',
    statusReversed: 'dibatalkan',
    addItem: 'Tambah Barang',
    itemName: 'Nama Barang',
    itemNameZh: 'Nama Mandarin',
    uom: 'Satuan',
    sellingPrice: 'Harga Jual',
    category: 'Kategori',
    subCategory: 'Sub Kategori',
    save: 'Simpan',
    stock: 'Stok',
    adjust: 'Sesuaikan',
    productCreated: 'Produk ditambahkan',
    productCreateFailed: 'Gagal menambahkan produk',
    retryLoad: 'Coba lagi',
    loadingProducts: 'Memuat produk…',
    noProductsYet: 'Belum ada produk.',
    nameRequired: 'Masukkan nama barang.',
    priceRequired: 'Masukkan harga jual lebih besar dari 0.',
    stockUpdateFailed: 'Gagal memperbarui stok',
    colName: 'Nama',
    colCategory: 'Kategori',
    colUom: 'Satuan',
    colPrice: 'Harga',
    colStock: 'Stok',
  },
}

export function strings(lang) {
  return STRINGS[lang] || STRINGS.EN
}
